# Generated by Django 3.2 on 2022-11-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='clean',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='taste',
            field=models.IntegerField(null=True),
        ),
    ]
