# Generated by Django 3.2 on 2022-11-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20221115_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='content',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='place',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='stufflist',
        ),
        migrations.AddField(
            model_name='checklist',
            name='cafeteria_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='checklist',
            name='menu_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
