# Generated by Django 3.2 on 2022-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(default='', max_length=32)),
                ('cafeteria', models.CharField(default='', max_length=32)),
                ('price', models.IntegerField(null=True)),
                ('type', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(default='', max_length=32)),
                ('kor_name', models.CharField(default='', max_length=32)),
                ('location', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=32)),
                ('operating_day', models.CharField(default='', max_length=32)),
                ('operating_time', models.CharField(default='', max_length=32)),
                ('notice_contents', models.CharField(default='', max_length=32)),
                ('notice_registered', models.CharField(default='', max_length=32)),
                ('lat', models.IntegerField(null=True)),
                ('lng', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(default='', max_length=32)),
                ('cafeteria_name', models.CharField(default='', max_length=32)),
                ('avg_taste', models.FloatField()),
                ('avg_quality', models.FloatField()),
                ('avg_cost', models.FloatField()),
                ('avg_clean', models.FloatField()),
                ('avg_quantity', models.FloatField()),
            ],
        ),
    ]
